### ISSUE TITLE
Criar projeto Django

### ISSUE THREAD

**Issue by samukasmk** [luizzenon/Chat_UDP#4]
Criar projeto django com crud definido

**Comment by jamesperes-zz** [comment]
Django 2.0 e Python 3.7

**Comment by jamesperes-zz** [comment]
Me fala o que precisa que eu crio aqui hoje

**Comment by luizzenon** [comment]
Oi @jamesperes . Eu não tenho muito parâmetro sobre criar Projeto Django. Criar eu aprendi no Tutorial das Django Girls. Mas não sei se tem que criar de uma forma personalizada. O @samukasmk tá compartilhando a experiência dele e ele que orientou a fazer essa Issue. Então vamos ver com ele. Se for simplesmente criar, eu posso fazer. Até é bom pra treinamento! ;)

**Comment by luizzenon** [comment]
Criado Projeto Django :)
